### PR TITLE
Pin g2clib

### PR DESCRIPTION
**Pull request by ocefpaf**
I could not get `pynio` to work with the latest `g2clib 1.6.0`, so I am pinning it here to the `1.5.*` version.

See https://github.com/conda-forge/g2clib-feedstock/pull/9

### CODE REVIEW

**Comment by david-ian-brown** [comment]
Hi Filipe,
FYI, PyNIO uses a modified version of the g2clib. I am not sure what kind
of error you encountered but I would be interested to know.
 -dave

**Comment by ocefpaf** [comment]
> FYI, PyNIO uses a modified version of the g2clib.

Interesting. Is that bundled in the code? I packages [this](https://github.com/conda-forge/g2clib-feedstock) before and version `g2clib 1.5.0` worked fine, but version `1.6.0` fails with:

```shell
g++ -pthread -shared -L/opt/conda/envs/_build_placehold_placehold_placehold_placehold_placehold_placeho/lib -Wl,-rpath=/opt/conda/envs/_build_placehold_placehold_placehold_placehold_placehold_placeho/lib,--no-as-needed -L/opt/conda/envs/_build_placehold_placehold_placehold_placehold_placehold_placeho/lib -D_BSD_SOURCE -D_XOPEN_SOURCE -I/opt/conda/envs/_build_placehold_placehold_placehold_placehold_placehold_placeho/include -I/opt/conda/envs/_build_placehold_placehold_placehold_placehold_placehold_placeho/include build/temp.linux-x86_64-2.7/niomodule.o  -Llibsrc -L/opt/conda/envs/_build_placehold_placehold_placehold_placehold_placehold_placeho/lib -L/opt/conda/envs/_build_placehold_placehold_placehold_placehold_placehold_placeho/lib -L/opt/conda/envs/_build_placehold_placehold_placehold_placehold_placehold_placeho/lib -Lbuild/temp.linux-x86_64-2.7 -lnio -ljpeg -lpng -lz -lnetcdf -lmfhdf -ldf -lhdf5_hl -lhdf5 -lcurl -lhdfeos -lGctp -lgrib2c -ljasper -ljpeg -lpng -lhdf5_hl -lhdf5 -lhe5_hdfeos -lGctp -lgdal -lproj -liconv -ljasper -ljpeg -lpng -lz -lgfortran -lgfortran -lpython2.7 -o build/lib.linux-x86_64-2.7/PyNIO/nio.so
/opt/rh/devtoolset-2/root/usr/bin/ld: cannot find -lgrib2c
collect2: error: ld returned 1 exit status
/opt/rh/devtoolset-2/root/usr/bin/ld: cannot find -lgrib2c
collect2: error: ld returned 1 exit status
error: Command "g++ -pthread -shared -L/opt/conda/envs/_build_placehold_placehold_placehold_placehold_placehold_placeho/lib -Wl,-rpath=/opt/conda/envs/_build_placehold_placehold_placehold_placehold_placehold_placeho/lib,--no-as-needed -L/opt/conda/envs/_build_placehold_placehold_placehold_placehold_placehold_placeho/lib -D_BSD_SOURCE -D_XOPEN_SOURCE -I/opt/conda/envs/_build_placehold_placehold_placehold_placehold_placehold_placeho/include -I/opt/conda/envs/_build_placehold_placehold_placehold_placehold_placehold_placeho/include build/temp.linux-x86_64-2.7/niomodule.o  -Llibsrc -L/opt/conda/envs/_build_placehold_placehold_placehold_placehold_placehold_placeho/lib -L/opt/conda/envs/_build_placehold_placehold_placehold_placehold_placehold_placeho/lib -L/opt/conda/envs/_build_placehold_placehold_placehold_placehold_placehold_placeho/lib -Lbuild/temp.linux-x86_64-2.7 -lnio -ljpeg -lpng -lz -lnetcdf -lmfhdf -ldf -lhdf5_hl -lhdf5 -lcurl -lhdfeos -lGctp -lgrib2c -ljasper -ljpeg -lpng -lhdf5_hl -lhdf5 -lhe5_hdfeos -lGctp -lgdal -lproj -liconv -ljasper -ljpeg -lpng -lz -lgfortran -lgfortran -lpython2.7 -o build/lib.linux-x86_64-2.7/PyNIO/nio.so" failed with exit status 1
Command failed: /bin/bash -x -e /opt/conda/conda-bld/work/pynio-1.5.0_beta20160623/conda_build.sh
```

I did not that the static library name changed from `libgrib2c.a` to `libg2c_v1.6.0.a`, but I did not dig into this and decided that pinning was the way to go for now.

**Comment by david-ian-brown** [comment]
Yes, the library name changed in the NCEP-provided Makefile for 1.6.0.  I
changed it back to the old name in our version of the library. Basically,
the version we use allows for more flexibility in the sign of longitudes in
the GRIB records. WMO says that for GRIB2 longitudes should always be
positive, but some people still put in negative longitudes so we try to
handle them.
It should still build without our changes though and the library name
change is probably the culprit.
 -dave

**Comment by ocefpaf** [comment]
Good to know. Since `pynio` is the only package using `g2clib` I can either rename it there or I can make a copy with the old name as a workaround. Although, ideally we should preserve the original name and patch `pynio` to find it.

**Comment by david-ian-brown** [comment]
We could probably do the source code changes to be more forgiving about longitudes as a patch as well.

**Comment by ocefpaf** [comment]
> We could probably do the source code changes to be more forgiving about longitudes as a patch as well.

:+1:

**Pull request merged**
