### PR TITLE
Fix building with hdf5 and migrate everything

### PR DESCRIPTION
**Pull request by fulminemizzega**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This fixes (at least on linux) #100, #90, maybe it helps with #114. 

See commit messages for more info, with these changes pynio builds fine at least with linux_64_numpy1.19python3.9.____cpython and linux_64_numpy1.21python3.10.____cpython
There are 101 passing tests during the build, with 506 warnings.

### CODE REVIEW

**Comment by fulminemizzega** [comment]
Tests are failing because http://test.opendap.org/opendap/data/nc/bears.nc does not work anymore. A few hours ago it was working fine, I hope it's not because of my test runs...

**Comment by hmaarrfk** [comment]
Try:

```
pytest -k test_opendap2
```

**Comment by hmaarrfk** [comment]
@conda-forge-admin please retender

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by fulminemizzega** [comment]
I think I do not understand how to do migrations correctly, the bot rerendered with older versions. In my fork there are no migration files in .ci_support commited to the tree

**Comment by hmaarrfk** [comment]
I think it is good to keep the rerender commits completely isolated from your changes. You can then rebase and cleanup your history with more ease

**Comment by hmaarrfk** [comment]
Are you interested in becoming a maintainer?

**Comment by fulminemizzega** [comment]
> Are you interested in becoming a maintainer?

First, thank you for your proposal. I do not know if it is a good idea, I've just improved a bit what I did back in January and sent a similar PR, I do not use any of this stuff and neither understand what it is used for (well, I understand it reads netCDF files, that's all). Back then I was playing with conda for the first time trying to reproduce and environment with newer packages and the first thing that failed was pynio, requiring an old hdf5 version. By luck I found about the compatibility macro, I tested it and for once instead of throwing everything away and filing an issue I decided to make a PR.
I know my way around a bit with git, python (dabbled with numpy and matplotlib) and C, but I'm not a python developer. I did this just for fun, being a maintainer implies that I have to be able to make time for this.. how strict are the requirements for being a maintainer?


> I think it is good to keep the rerender commits completely isolated from your changes. You can then rebase and cleanup your history with more ease

I use git in my personal projects and never had to rebase anything, I can try. I do now know if I understand completely what you said, I've made commits with changes and a re-render like 45398aa and 5488686... do you mean that also these commits should be changed?

**Comment by hmaarrfk** [comment]
I feel like the requirements are quite loose.

Ultimately, if you need this even a little bit, it is in your interest to keep it alive. 

Otherwise, do you use this package at all? I'm somewhat interested in archiving this package since it hasn't been refreshed in a while.

But... Maybe we can merge this and this about this problem later.

**Comment by fulminemizzega** [comment]
> Otherwise, do you use this package at all? I'm somewhat interested in archiving this package since it hasn't been refreshed in a while.

A research friend showed me this ugly setup with a hand-made VM with many (many) dependencies, I tried to reproduce it with conda, after trying for 2 days I gave up, but at least I got pynio updated. I think the current solution is to ship back and forth a VM that keeps growing in size (I did not know before how hopeless it was).
So, no, I do not use at all.
> But... Maybe we can merge this and this about this problem later.

Now at least it can be refreshed, maybe having found these fixes will make it easier in the future.
Was your suggestion about isolating rerendering from other changes a future advice or is it better if I rebase before merging this PR?

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
See https://github.com/conda-forge/av-feedstock/pull/53

* One commit where I touched every line of code.
* The second commit where the rerender happened. 

You can then delete the rerenders when you want to cleanup, or just sqaush them to better understnad what your modifications were

**Comment by fulminemizzega** [comment]
> Try:
> 
> ```
> pytest -k "not test_opendap2"
> ```

Link for the file used in this test is now up again, I reverted this change. I also added another patch that fixes a subset of the warnings from numpy, does the build number need to be incremented?. Can new commits still be added to this PR?

**Comment by hmaarrfk** [comment]
>  Can new commits still be added to this PR?

No. please open a new PR.

At this stage you are doing the maintainers job. so please add yourself as one.

**Comment by hmaarrfk** [comment]
"a maintainer's job"

**Pull request merged**
